name: caresens_integration Build

on:
  push:
    branches: [caresens_integration]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install Fastlane
        run: gem install fastlane
      - name: Build CareSens integration
        env:
          TEAMID: ${{ secrets.TEAMID }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
        run: fastlane caresens_integration
